const blogData = [
    {
 id: 1,
       image: "/images/university.jpg",
      title: "NUC secures 40 million loan to boost ICT project in 10 federal universities",
     
      content:
        "School digital platforms help track student performance, assignments, class attendance, and more...",
      rating: 4,
      date: "december 2025",
      link :"https://www.newsnow.com/share?data=eyJwdWJJZCI6IkJVU0lORVNTSEFMTE1BUksiLCJtbmlkIjoiNDI5MzgiLCJpbWdTaXplcyI6eyJkbCI6MSwiZDIiOjEsImQiOjEsImQxIjoxLCJtbCI6MX0sImlkIjoiMTI5NjQxMDU0MiIsInRpdGxlIjoiTlVDIHNlY3VyZXMg4oKsNDBtIGxvYW4gdG8gYm9vc3QgSUNUIHByb2plY3RzIGluIDEwIGZlZGVyYWwgdW5pdmVyc2l0aWVzIiwidGltZXN0YW1wIjoiMTc2NDk0NDcwMiIsInVybCI6Imh0dHBzOi8vaGFsbG1hcmtuZXdzLmNvbS9udWMtc2VjdXJlcy1lNDBtLWxvYW4tdG8tYm9vc3QtaWN0LXByb2plY3RzLWluLTEwLWZlZGVyYWwtdW5pdmVyc2l0aWVzLyIsInB1Yk5hbWUiOiJCdXNpbmVzcyBIYWxsbWFyayJ9&sgt=shv2&sg=59cbb001&utm_medium=shared&utm_source=newsnow&utm_campaign=copy&sid=6",


      likes: 0,
      liked: false,
    },
    {
      id: 2,
      title: "Arts, commercial, science students free to choose any WAEC subjects - FG",
      image: "/images/WhatsApp Image 2025-12-09 at 13.42.39_80acaf81.jpg",
      content:
        "The federal Government has reaffirmed that senior secondary school students whether in arts, commercial or science are free to register any approved subject of...",
      rating: 5,
      date: "December 2025",
      link:"https://guardian.ng/education/subjects-combinations/",
      likes: 0,
      liked: false,
    },
    {
    id: 3,
    title: "No Restriction in New curriculum, FG Assures students",
    image: "/images/education.png",
    content:"The Federal Government has issued fresh clarification on subject selection under the revised senior secondary school curriculum,...",
    date:"December 2025",
    link : "https://thenigeriaeducationnews.com/2025/12/07/no-restrictions-in-new-curriculum-fg-assures-students/",
    likes :0,
},
{
id:4,
title: "Senate halts WAEC curriculum changes over fears for 2026 candidates ",
image:"/images/waec.jpg",
content :"The senate on tuesday waded into a brewing crisis in Nigeria's educatonal sector, summoning the minister of Education.....",
date:"December 2025",
link: "https://guardian.ng/education/senate-halts-waec-curriculum-change-over-fears-for-2026-candidates/",
likes : 0,
},
{
  id:5,
  title: "Effcient resources management key to qualitative education - AAUA don, Akinfolarin",
  image : "/images/WhatsApp Image 2025-12-11 at 19.29.41_4e5ec075.jpg",
  content:" A professor of Educational Management has emphasised the role of resource management...",
  date:"December 2025",
  link:"https://guardian.ng/education/efficient-resource-management-key-to-qualitative-education-aaua-don-akinfolarin/",
  likes:0,
},
 {
 id:6,
 title:"Experts urge students to embrace emerging technologies",
 image:"/images/WhatsApp Image 2025-12-11 at 22.30.35_a307024e.jpg",
 content:"Speakers at the seventh international conference on Entrepreneurship at mountain top university....",
 date:"December 2025",
 link:"https://punchng.com/experts-urge-students-to-embrace-emerging-technologies/",
 likes:0,
 },
 {
  id:7,
  title:"JAMB releases registration guidelines for 2026 UTME",
  image:"/images/WhatsApp Image 2025-12-11 at 22.38.52_ba565c69.jpg",
  content:"The Joint Admissions and matriculation Board has released detailed guidelines....",
  date:"December 2025",
  link:"https://punchng.com/jamb-releases-registration-guidelines-for-2026-utme/",
  likes:0,
 },
 {
  id:8,
  title:"Firms offers two-year scholarship to rescued schoolchildren",
  image:"/images/WhatsApp Image 2025-12-11 at 22.45.35_7b70879c.jpg",
  content:"EduReach, an online educational platform, has announced....",
  date:"December 2025",
  link:"https://punchng.com/firm-offers-two-year-scholarship-to-rescued-schoolchildren/",
  likes:0,

 },
 {
  id :9,
  title:"Essay competition",
  image:"/images/WhatsApp Image 2025-12-12 at 11.26.22_38fa220d.jpg",
  content:"Jemila Abubakar Memorial Essay Competition 2026",
  date:"December 2025",
  link:"https://myschool.ng/news/category/scholarships",
  likes:0,
 },
 {
  id:10,
  title:"Scholarship Previews",
  image :"/images/WhatsApp Image 2025-12-08 at 22.25.01_f0e355cc.jpg",
  content:"Chevenings Scholarships...",
  date:"December 2025",
  link:"https://www.chevening.org/scholarships/",
  likes:0,
 },
 {
  id:11,
  title:"Dangote Scholarships Opportunity",
  image:"/images/WhatsApp Image 2025-12-12 at 11.42.03_4f227558.jpg",
  content:"Dangote launches N1trn scholarship scheme for 1.3m students....",
  date:"December 2025",
  link:"https://share.google/7aPpWx90ugsO7JpYD",
  likes:"0",
 },
 {
  id:12,
  title:"Greensprings Scholarships",
  image:"/images/WhatsApp Image 2025-12-12 at 11.48.50_df67ed21.jpg",
  content:"Greensprings School opens scholarship application for 2026/2027",
  date:"December 2025",
  link :"https://share.google/vqtLD8VWxIXysVpEJ",
  likes:0,
 },
 {
  id:13,
  title:"Creator Award",
  image:"/images/WhatsApp Image 2025-12-12 at 11.33.45_569fa01f.jpg",
  content:"African Tech educator, Boye, wins tiktok's Education Creator Award",
  date:"December 2025",
  link:"https://guardian.ng/education/african-tech-educator-boye-wins-tiktoks-education-creator-award/",
  likes:0,
 },
 {
  id:14,
  title:"BHLA Empowerment programme",
  image:"/images/WhatsApp Image 2025-12-12 at 11.32.48_4ef44cd4.jpg",
  content:"BHLA partners YABATECH to empower over 1000 young creatives in Lagos",
  date:"December 2025",
  link:"https://guardian.ng/education/bhla-partners-yabatech-to-empower-over-1000-young-creatives-in-lagos/",
  likes:0,
 },
 {
  id:15,
  title:"Resume Mistakes",
  image:"/images/WhatsApp Image 2025-12-12 at 12.16.00_1c6a3809.jpg",
  content:"Common resume mistakes graduate make and how to avoid them",
  date:"December 2025",
  link:"https://guardian.ng/education/9-common-resume-mistakes-graduates-make-and-how-to-avoid-them/",
  likes:0,
 },
];
export default blogData;